### PR TITLE
[readme-file-changes]

### PR DESCRIPTION
**Pull request by nileshkr17**
#22  done

### CODE REVIEW

**Comment by nileshkr17** [comment]
@mezotv 
https://github.com/nileshkr17/Crypto-Helper

**Comment by mezotv** [comment]
Woah cool! Looks good but i think you can remove the infinitybots card thats outdated anyways

**Review by mezotv — CHANGES_REQUESTED** [review]
Remove the InfinityBots please

**Comment by nileshkr17** [comment]
@mezotv please check now,
also do you want any help in 
https://developersdungeon.xyz/ this?
I would love to contribute

**Comment by mezotv** [comment]
Sure you're always welcome to contribute

**Review by mezotv — APPROVED** [review]
Looks amazing! Thanks alot!

**Comment by mezotv** [comment]
You can find the websites repo here: https://github.com/Developer-Dungeon-Studio/DungeonWebsite

**Comment by nileshkr17** [comment]
hey @mezotv  i am not able to see myself as a contributor of Developer -Dungeon.
It's icon should reflect in my organization list as I have contributed to it,  right?

**Comment by mezotv** [comment]
The icon only reflects when you are a member of the organization. I can add you as one though

**Pull request merged**
